vich_uploader:
    db_driver: orm
    mappings:
        files:
            uri_prefix: '%app.path.files%'
            upload_destination: '%kernel.project_dir%/public%app.path.files%'
            namer: vich_uploader.namer_origname # permet d'avoir un nom d'image unique
            inject_on_load: true # injecte l'image au chargement du formulaire
            delete_on_remove: true # suppression du fichier à la suppression de l’entité
            delete_on_update: false # suppression du fichier quand un nouveau fichier est envoyé

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
