<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;
use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * ActualiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActualiteRepository extends NestedTreeRepository
{

    public function getListes()
    {
        $query = $this->createQueryBuilder('a')
            ->orderBy('a.titre', 'ASC')
            ->getQuery()
        ;

        return $query->getResult();
    }

    
}
