#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#admin_page_new:
#    path:     /new
#    defaults: { _controller: NormeBundle:DossierNorme:new }

admin_page:
    path: /
    controller: App\Controller\CoreController::indexNovate

admin_actualite_new:
    path: /new
    controller: App\Controller\ActualiteController::newActualite

admin_actualite_list:
    path: /list
    controller: App\Controller\ActualiteController::listActualite
    