<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHqqGEtq\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHqqGEtq/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHqqGEtq.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHqqGEtq\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHqqGEtq\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HqqGEtq',
    'container.build_id' => 'cac24320',
    'container.build_time' => 1634698752,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHqqGEtq');
