<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWUSeb0x\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWUSeb0x/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWUSeb0x.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWUSeb0x\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWUSeb0x\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WUSeb0x',
    'container.build_id' => '51aaff1e',
    'container.build_time' => 1634698241,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWUSeb0x');
