<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAU5owCs\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAU5owCs/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAU5owCs.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAU5owCs\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAU5owCs\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'AU5owCs',
    'container.build_id' => 'ba4723ca',
    'container.build_time' => 1634627929,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAU5owCs');
